### ISSUE TITLE
Reading configuration files with incomplete map name

### ISSUE THREAD

**Issue by Alexeyt89** [alliedmodders/stripper-source#18]
I suggest to add support for configuration files with incomplete map names.
Example:
de_.cfg // Such config file would be applied for all de_ maps after applying global_filter.cfg and before applying configs with full name. Here is a way to implement it:

Add this code to support.cpp->parse_map after global_filters.cfg reader:

    char subName[256] = "\0";
    const char* mapName = map;
    
    size_t underscoreIndex = 0;
    while(underscoreIndex != 255)
    {
    	if(*mapName == '\0')
    		break;

    	subName[underscoreIndex++] = *mapName;
    	if(*mapName != '_')
    	{
    		++mapName;
    		continue;
    	}
    
    	subName[underscoreIndex] = '\0';
    	
    	stripper_game.path_format(path,
	            sizeof(path),
	            "%s/%s/maps/%s.cfg",
	            stripper_game.game_path,
	            stripper_game.stripper_cfg_path,
	            subName);

    	fp = fopen(path, "rt");
    	if (fp)
    	{
    		fclose(fp);
    		g_Stripper.ApplyFileFilter(path);
    	}
    
    	break;
    }

**Comment by Adrianilloo** [comment]
I completely second the basic idea, as I've realized the need for my server to split some edits done in `global_filters.cfg` as a way to cover multiple maps for a certain gamemode without happening on the rest.

But I think manually checking for underscore is a too highly coupled, non-generic approach. Instead I think it would be almost completely agreeable to replace the default pattern matching with partial searches (from the name beginning).
