### ISSUE TITLE
Try compile but failed

### ISSUE THREAD

**Issue by Owned67** [alliedmodders/stripper-source#4]
gcc -I. -Ipcre -I../mmsource-1.10/core/sourcehook Release/parser.o Release/support.o -m32 -lm -ldl pcre/.libs/libpcre.a -static-libgcc -shared -o Release/stripper.core.so
/usr/bin/ld: i386:x86-64 architecture of input file `pcre/.libs/libpcre.a(pcre_compile.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file`pcre/.libs/libpcre.a(pcre_exec.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `pcre/.libs/libpcre.a(pcre_globals.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file`pcre/.libs/libpcre.a(pcre_newline.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `pcre/.libs/libpcre.a(pcre_study.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file`pcre/.libs/libpcre.a(pcre_tables.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `pcre/.libs/libpcre.a(pcre_try_flipped.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file`pcre/.libs/libpcre.a(pcre_chartables.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `pcre/.libs/libpcre.a(pcre_fullinfo.o)' is incompatible with i386 output
collect2: error: ld returned 1 exit status

can you help me please?

**Comment by Drifter321** [comment]
You are linking against the 64bit pcre bins from your system  instead of the ones included in the repo. You should use AMBuild as that is what is used normally for building and has all the paths set up.

**Comment by Owned67** [comment]
edit:

if  i use ambuild, i get:
~/l4d2/stripper-source/build$ python ../configure.py --enable-optimize
Checking c compiler (vendor test gcc)... ['gcc', 'test.c', '-o', 'test']
found gcc version 4.7
Checking cxx compiler (vendor test gcc)... ['g++', '-fno-exceptions', '-fno-rtti', 'test.cxx', '-o', 'testp']
found gcc version 4.7
git rev-list --count HEAD /home/games/l4d2/stripper-source
Adding job stripper.core.
Adding job stripper.16.l4d2.
Adding job stripper_mm_i486.
Adding job package.
games@debian:~/l4d2/stripper-source/build$ ambuild
Error: folder was not configured for AMBuild.

**Comment by Drifter321** [comment]
Sorry for the late reply, stripper has a very old ambuild version. It appears you have to run the build.py that is created inside the directory (I also didnt know this). But it can be seen in the startbuild.pl inside of the buildbot folder.
