### ISSUE TITLE
Stripper causing crashes on surf servers?

### ISSUE THREAD

**Issue by skyprah** [alliedmodders/stripper-source#6]
https://crash.limetech.org/stats/ade67a3d7149c9fc3761df354f7b5bb3a820d828eecef2151b9ca26a25cc7b66e4241ff9

IT2A-CO45-DCET
https://crash.limetech.org/it2aco45dcet

Not sure if related, but crashes occur on map change. I've been told its most likely due to stripper. There is no common maps, it is completely random. Thanks

**Comment by Drifter321** [comment]
This is likely not related to Stripper.
