### ISSUE TITLE
CSGO game_text newline doesn't work

### ISSUE THREAD

**Issue by TianQiBuTian** [alliedmodders/stripper-source#7]
Screenshot:http://steamcommunity.com/sharedfiles/filedetails/?id=890711316
This is the game_text from used hammer

I put this game_text in stripper config, but it doesn't work

> add:
{
	"hammerid" "2264435"
	"origin" "-14267.4 -11618.4 -1016"
	"y" ".3"
	"x" ".02"
	"targetname" "Map_HudHint"
	"spawnflags" "1"
	"holdtime" "4"
	"fxtime" ".1"
	"fadeout" "3"
	"fadein" ".02"
	"effect" "2"
	"color2" "4 4 193"
	"color" "9 156 236"
	"channel" "4"
	"classname" "game_text"
	"OnUser1" "!selfSetTextze_FFXII_Paramina_Rift
Map by Slayerdragon
& h4sArD/Noctali
Models by K.
Thanks to:
 Cuniczek
 d'Maniak
 JorisCeoen
 Sgt. zaCade
 LaStation
 George
 Lev
 Schicksal01"
	"OnUser1" "!selfDisplay0.011"
}

I used stripper_dump can't see the first OnUser1

> {
"hammerid" "2264435"
"origin" "-14267.4 -11618.4 -1016"
"y" ".3"
"x" ".02"
"targetname" "Map_HudHint"
"spawnflags" "1"
"holdtime" "4"
"fxtime" ".1"
"fadeout" "3"
"fadein" ".02"
"effect" "2"
"color2" "4 4 193"
"color" "9 156 236"
"channel" "4"
"classname" "game_text"
"OnUser1" "!selfDisplay0.011"
}

Can you fix this problem?

**Comment by asherkin** [comment]
You can't set the same key (`OnUser1`) to multiple different values.

**Comment by TianQiBuTian** [comment]
So how should I make this?

**Comment by Drifter321** [comment]
This isnt a support area, you should ask on the forums.
