### ISSUE TITLE
Crashes on 29/03/2019

### ISSUE THREAD

**Issue by JamsRepos** [alliedmodders/stripper-source#9]
There's been reports of stripper crashing servers after the recent update, can we confirm or deny?

**Comment by Furchee** [comment]
Can confirm it crashes the server now. I've tried multiple builds as well. Guess it's finally time for an update.

**Comment by JamsRepos** [comment]
Linux: http://www.bailopan.net/stripper/snapshots/1.2/stripper-1.2.2-git128-linux.tar.gz
Windows: http://www.bailopan.net/stripper/snapshots/1.2/stripper-1.2.2-git128-windows.zip
